version: "3.8"

volumes:
  postgres:

services:
#  nginx:
#    build:
#      context: .
#      dockerfile: "Dockerfile.nginx"
#    container_name: chat_nginx
#    ports:
#      - "8080:8080"
#    links:
#      - chat_service


  db:
    image: postgres:16
    container_name: "chat_db"
    env_file:
      - .env_dev
    ports:
      - "5432:5432"

  chat_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_dev
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
